//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    
    public partial class TypesOfCar : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    	protected void OnPropertyChanged(string propertyName)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    
        public TypesOfCar()
        {
            this.CarRentalRecords = new ObservableCollection<CarRentalRecord>();
        }
    
        int _Id;
        public int Id 
        {
            get { return _Id; }
            set
            {
                _Id = value;
                OnPropertyChanged("Id");
            }
        }
        string _Make;
        public string Make 
        {
            get { return _Make; }
            set
            {
                _Make = value;
                OnPropertyChanged("Make");
            }
        }
        string _Model;
        public string Model 
        {
            get { return _Model; }
            set
            {
                _Model = value;
                OnPropertyChanged("Model");
            }
        }
        string _VIN;
        public string VIN 
        {
            get { return _VIN; }
            set
            {
                _VIN = value;
                OnPropertyChanged("VIN");
            }
        }
        string _LicensePlateNumber;
        public string LicensePlateNumber 
        {
            get { return _LicensePlateNumber; }
            set
            {
                _LicensePlateNumber = value;
                OnPropertyChanged("LicensePlateNumber");
            }
        }
        Nullable<int> _Year;
        public Nullable<int> Year 
        {
            get { return _Year; }
            set
            {
                _Year = value;
                OnPropertyChanged("Year");
            }
        }
    
        public virtual ObservableCollection<CarRentalRecord> CarRentalRecords { get; set; }
    }
}
