//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    
    public partial class UserRole : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    	protected void OnPropertyChanged(string propertyName)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    
        int _id;
        public int id 
        {
            get { return _id; }
            set
            {
                _id = value;
                OnPropertyChanged("id");
            }
        }
        int _userid;
        public int userid 
        {
            get { return _userid; }
            set
            {
                _userid = value;
                OnPropertyChanged("userid");
            }
        }
        int _roleid;
        public int roleid 
        {
            get { return _roleid; }
            set
            {
                _roleid = value;
                OnPropertyChanged("roleid");
            }
        }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
